# Generated by Django 4.2.3 on 2023-09-26 00:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("news", "0003_alter_news_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="news",
            name="categories",
        ),
        migrations.AddField(
            model_name="news",
            name="categories",
            field=models.ManyToManyField(
                related_name="news", to="news.categories"
            ),
        ),
    ]
