# Generated by Django 4.2.3 on 2023-09-26 00:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("news", "0004_remove_news_categories_news_categories"),
    ]

    operations = [
        migrations.AlterField(
            model_name="news",
            name="created_at",
            field=models.DateField(),
        ),
    ]
