# Generated by Django 4.2.3 on 2023-09-26 18:00

from django.db import migrations, models
import news.validators


class Migration(migrations.Migration):
    dependencies = [
        ("news", "0005_alter_news_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="news",
            name="title",
            field=models.CharField(
                max_length=200, validators=[news.validators.validate_min_words]
            ),
        ),
        migrations.AlterField(
            model_name="users",
            name="email",
            field=models.EmailField(max_length=200),
        ),
    ]
